server:
  port: 8081
  shutdown: graceful
  netty:
    connection-timeout: 2s
    idle-timeout: 15s

spring:
  application:
    name: vote-processor
  lifecycle:
    timeout-per-shutdown-phase: 15s
  cassandra:
    username: root
    password: 1234
    ssl:
      enabled: false
    port: 9042
    keyspace-name: vote_processor
    schema-action: create_if_not_exists
    request:
      timeout: 2000
    contact-points: localhost
    connection:
      connect-timeout: 5000
      init-query-timeout: 5000
    pool:
      idle-timeout: 5000
    local-datacenter: datacenter1
  kafka:
    bootstrap-servers: localhost:9092
    template:
      default-topic: vote-topic