server:
  port: 8080
  shutdown: graceful
  netty:
    connection-timeout: 2s
    idle-timeout: 15s

spring:
  application:
    name: vote-gateway
  lifecycle:
    timeout-per-shutdown-phase: 15s
  r2dbc:
    url: r2dbc:mysql://localhost:3306/weverse?sslMode=DISABLED
    username: root
    password: 1234
    pool:
      enabled: true
      max-size: 20
      initial-size: 5
      validation-query: SELECT 1
  data:
    r2dbc:
      repositories:
        enabled: true
    redis:
      host: localhost
      port: 6379
      database: 0
      connect-timeout: 2s
      timeout: 1s
  cloud:
    gateway:
      routes:
        - id: vote_route
          uri: lb://vote-service
          predicates:
            - Path=/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter:
                  replenishRate: 1 # 초당 1개의 토근이 생성됨
                  burstCapacity: 1
                  requestedTokens: 1
                key-resolver: "#{@userKeyResolver}"

vote:
  process-service-uri: "http://localhost:8081"
